### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by AndrewIsh** [bywatersolutions/koha-plugin-unused-authority-check#8]
Attempting to install this plugin fails with (on Koha 20.11.07.000):
```
Can't call method "isa" on an undefined value at /usr/share/koha/lib/Koha/Plugins/Base.pm line 300.
```
After much poking around, it turns out that this commit appears to have broken it:
https://github.com/bywatersolutions/koha-plugin-unused-authority-check/commit/7642969376efe3bcc0c3b26bca791e5695ea9e8e#diff-0d7cdc37e63181934875608f446115fdbc9c9f41587184e0405f670741e9ca0d

This commit removes the `install` function, so `Base.pm` thinks it can't install, tries to upgrade and fails because `_version_compare` isn't passed the arguments it expects.

**Comment by kylemhall** [comment]
Thanks for letting us know! This should be fixed in version 1.5.10!
